### ISSUE TITLE
ES 1.6 ClassNotFound

### ISSUE THREAD

**Issue by monowai** [searchbox-io/Jest#211]
Since upgrading to ES 1.6, I get the following exception in my tests
```
java.lang.NoClassDefFoundError: org/apache/http/ssl/SSLContexts
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.getSocketFactory(SSLConnectionSocketFactory.java:172)
	at io.searchbox.client.config.HttpClientConfig$Builder.<init>(HttpClientConfig.java:88)
```

Code being executed is:
```
HttpClientConfig clientConfig = new HttpClientConfig.Builder("http://localhost:" + properties.get("es.http.port")).build();
```
Downgrading to 1.5 makes the issue go away. The MVN dependency:
```
        <dependency>
            <groupId>io.searchbox</groupId>
            <artifactId>jest</artifactId>
            <version>0.1.6</version>
            <scope>test</scope>
        </dependency>
````

**Comment by kramer** [comment]
There were no errors when I ran the build with ES 1.6.0, please check your dependency tree for duplicate older version imports of `org.apache.http*`packages.

**Comment by monowai** [comment]
Thanks @kramer. My project also uses Apache Tika which was upgraded. Both Searchbox and Tika use httpcore. Excluding HTTPCORE seems to have fixed it with no adverse consequence. In case others encounter this issue:
```
        <dependency>
            <groupId>org.apache.tika</groupId>
            <artifactId>tika-parsers</artifactId>
            <version>${tika.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.httpcomponents</groupId>
                    <artifactId>httpcore</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
